name: "π³ DevOps / μΈν”„λΌ μ„¤μ •"
description: "λ°°ν¬, CI/CD, μΈν”„λΌ κµ¬μ¶• λ° ν”„λ΅μ νΈ μλ™ν™” μ‘μ—…μ„ μ •μν•©λ‹λ‹¤."
title: "[DevOps] "
labels: ["π³ DevOps"]
body:
  - type: textarea
    id: work-summary
    attributes:
      label: "π“„ μ‘μ—… μ”μ•½"
      description: "μ–΄λ–¤ μΈν”„λΌ/μλ™ν™” μ‘μ—…μ„ μ§„ν–‰ν•λ”μ§€ κ°„κ²°ν•κ² μ„¤λ…ν•΄μ£Όμ„Έμ”."
      placeholder: "μ: GitHub Actionsλ¥Ό μ΄μ©ν• μ΄μ ν™κ²½ λ°°ν¬ νμ΄ν”„λΌμΈ κµ¬μ¶•"
    validations:
      required: true
  - type: textarea
    id: infrastructure-context
    attributes:
      label: "π—οΈ λ°°κ²½ λ° κΈ°μ  μ¤νƒ"
      description: "μ‘μ—…μ΄ ν•„μ”ν• λ°°κ²½κ³Ό μ‚¬μ©ν•  λ„κµ¬(Docker, K8s, Jenkins λ“±)λ¥Ό μ‘μ„±ν•΄μ£Όμ„Έμ”."
      placeholder: |
        - λ°°κ²½: ν„μ¬ μλ™ λ°°ν¬ λ°©μ‹μΌλ΅ μΈν•΄ λ°°ν¬ μ†λ„κ°€ λλ¦¬κ³  μ‹¤μκ°€ λ°μƒν•¨.
        - λ€μƒ: AWS EC2, Docker, GitHub Actions
    validations:
      required: true
  - type: textarea
    id: implementation-details
    attributes:
      label: "π’΅ μƒμ„Έ κµ¬ν„ κ³„ν"
      description: "μ–΄λ–»κ² ν™κ²½μ„ κµ¬μ„±ν•κ±°λ‚ μλ™ν™”ν•  κ²ƒμΈμ§€ κΈ°μ μ μΈ μ„Έλ¶€ μ‚¬ν•­μ„ μ„μ ν•΄μ£Όμ„Έμ”."
      placeholder: |
        - CI: main λΈλμΉ Push μ‹ λΉλ“ λ° ν…μ¤νΈ μλ™ν™”
        - CD: λΉλ“ μ™„λ£ ν›„ Docker μ΄λ―Έμ§€λ¥Ό ECRμ— ν‘Έμ‹ν•κ³  μ΄μ μ„λ²„μ— λ΅¤λ§ μ—…λ°μ΄νΈ μ μ©
    validations:
      required: true
  - type: textarea
    id: tasks
    attributes:
      label: "β… μ„Έλ¶€ μ‘μ—… λ©λ΅ (To-Do)"
      description: "μ™„λ£ν•΄μ•Ό ν•  μ„Έλ¶€ μ‘μ—…λ“¤μ„ μ²΄ν¬λ¦¬μ¤νΈλ΅ μ‘μ„±ν•΄μ£Όμ„Έμ”."
      placeholder: |
        - [ ] Dockerfile μ‘μ„± λ° μµμ ν™”
        - [ ] CI/CD μ¤ν¬λ¦½νΈ(.yml) μ‘μ„±
        - [ ] ν™κ²½ λ³€μ(Secrets) μ„¤μ •
        - [ ] λ°°ν¬ ν…μ¤νΈ λ° κ²°κ³Ό ν™•μΈ
    validations:
      required: true